In [2]:
# American College Insights

# Data Source: https://www.kaggle.com/datasets/jessemostipak/college-tuition-diversity-and-pay

In [5]:
import pandas as pd

historical_tuition = 'archive (1)/historical_tuition.csv'

df = pd.read_csv(historical_tuition)

df.head()

               type     year     tuition_type  tuition_cost
0  All Institutions  1985-86     All Constant         10893
1  All Institutions  1985-86  4 Year Constant         12274
2  All Institutions  1985-86  2 Year Constant          7508
3  All Institutions  1985-86      All Current          4885
4  All Institutions  1985-86   4 Year Current          5504

In [6]:
tuition_income = 'archive (1)/tuition_income.csv'

df = pd.read_csv(tuition_income)

df.head()

,name,state,total_price,year,campus,net_cost,income_lvl
0,Piedmont International University,NC,20174,2016,On Campus,11475.00000,"0 to 30,000"
1,Piedmont International University,NC,20174,2016,On Campus,11451.00000,"30,001 to 48,000"
2,Piedmont International University,NC,20174,2016,On Campus,16229.00000,"48_001 to 75,000"
3,Piedmont International University,NC,20174,2016,On Campus,15592.00000,"75,001 to 110,000"
4,Piedmont International University,NC,20514,2017,On Campus,11668.39249,"0 to 30,000"

In [7]:
salary_potential = 'archive (1)/salary_potential.csv'

df = pd.read_csv(salary_potential)

df.head()

,rank,name,state_name,early_career_pay,mid_career_pay,make_world_better_percent,stem_percent
0,1,Auburn University,Alabama,54400,104500,51.0,31
1,2,University of Alabama in Huntsville,Alabama,57500,103900,59.0,45
2,3,The University of Alabama,Alabama,52300,97400,50.0,15
3,4,Tuskegee University,Alabama,54500,93500,61.0,30
4,5,Samford University,Alabama,48400,90500,52.0,3